apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        version: "1.0"  # Specify the version here
    spec:
      containers:
        - name: demo
          image: swr.af-south-1.myhuaweicloud.com/ralf2/demo:image-version
          ports:
            - containerPort: 3000
