apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30007
